const CHANGE_BANNER = 'recommend/CHANGE_BANNER'

const CHANGE_RECOMMEND_LIST = 'recommend/RECOMMEND_LIST'

const CHANGE_ENTER_LOADING = 'recommend/CHANGE_ENTER_LOADING'

export {
    CHANGE_BANNER,
    CHANGE_RECOMMEND_LIST,
    CHANGE_ENTER_LOADING
}